import os
import sys
import subprocess
import pandas as pd
import streamlit as st

from src.journal import add_trade, load_journal, close_trade
from src.journal import init_db

init_db()

st.set_page_config(page_title="Personal Investment Research Desk", layout="wide")
st.title("Personal Investment Research Platform")
st.caption("A local investment support system for manual traders: track stocks, build plans, log trades, and review performance.")


def run_py(script, *args):
    cmd = [sys.executable, script, *args]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result


def load_csv(path):
    if os.path.exists(path):
        return pd.read_csv(path)
    return None


# Top instructions
with st.expander("Read this first if this is your first time using the system", expanded=True):
    st.markdown("""
### What is this system for?
This is a locally run investment support system designed for users who continue to place trades manually through CIBC or other brokerage platforms.

### What will it NOT do?
- It will not automatically buy or sell stocks for you
- It will not connect directly to CIBC for automated order placement
- It will not make final investment decisions on your behalf

### What CAN it help you do?
- Update market price data
- Generate a watchlist
- Generate a trade plan
- View backtest results
- Read SEC filing summaries
- Record real trades
- Conduct weekly reviews

### Recommended workflow
1. Click “Update Price Data” first each day
2. Then review the “Watchlist” and “Trade Plan”
3. After making actual trades, record them in the “Trade Journal”
4. At the end of each week, check the “Weekly Review”
    """)

col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("1. Daily Update")
    st.caption("After market close, it is recommended to click these buttons in order to refresh your research data.")

    if st.button("1) Update Price Data"):
        r = run_py("src/ingest_prices.py")
        if r.returncode == 0:
            st.success("Price data updated successfully")
        else:
            st.error(r.stderr or r.stdout)

    if st.button("2) Generate Watchlist"):
        r = run_py("src/score_watchlist.py")
        if r.returncode == 0:
            st.success("Watchlist updated successfully")
        else:
            st.error(r.stderr or r.stdout)

    if st.button("3) Generate Trade Plan"):
        r = run_py("src/trade_plan.py")
        if r.returncode == 0:
            st.success("Trade plan generated successfully")
        else:
            st.error(r.stderr or r.stdout)

    if st.button("4) Update Filing Summaries"):
        r = run_py("src/edgar_summary.py")
        if r.returncode == 0:
            st.success("Filing summaries updated successfully")
        else:
            st.error(r.stderr or r.stdout)

with col2:
    st.subheader("2. Strategy Check")
    st.caption("Used to test whether the strategy worked historically. Past performance does not guarantee future results.")

    with st.form("backtest_form"):
        bt_ticker = st.text_input("Enter ticker symbol for backtest", value="SPY")
        bt_submit = st.form_submit_button("Run Single-Stock Backtest")
        if bt_submit:
            r = run_py("src/backtest_bt.py", bt_ticker)
            if r.returncode == 0:
                st.success("Single-stock backtest completed")
            else:
                st.error(r.stderr or r.stdout)

    if st.button("Run Portfolio Backtest"):
        r = run_py("src/backtest_portfolio.py")
        if r.returncode == 0:
            st.success("Portfolio backtest completed")
        else:
            st.error(r.stderr or r.stdout)

with col3:
    st.subheader("3. System File Status")
    st.caption("These files are auto-generated by the system and support the data displayed on the interface.")

    for f in [
        "reports/watchlist.csv",
        "reports/trade_plan.csv",
        "reports/backtest_metrics.csv",
        "reports/backtest_portfolio_metrics.csv",
        "reports/backtest_portfolio_equity.csv",
        "reports/edgar_summary.csv",
        "reports/weekly_review.csv",
        "reports/weekly_review.txt",
        "reports/weekly_diagnostics.csv",
    ]:
        label = f.replace("reports/", "")
        st.write("✅" if os.path.exists(f) else "⬜", label)

st.divider()

tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs(
    ["Watchlist", "Trade Plan", "Backtest Results", "Filing Summaries", "Trade Journal", "Weekly Review"]
)

with tab1:
    st.subheader("Watchlist")
    st.caption("This is the current list of stocks selected by the system based on predefined rules. Higher scores generally indicate stronger trend or performance characteristics.")

    df = load_csv("reports/watchlist.csv")
    if df is not None:
        rename_map = {
            "ticker": "Ticker",
            "close": "Latest Price",
            "score": "Composite Score",
            "ma50": "50-Day MA",
            "ma200": "200-Day MA",
            "ret_252": "1-Year Return",
            "vol_60": "60-Day Volatility",
            "date": "Date",
        }
        df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})
        st.dataframe(df, use_container_width=True)
    else:
        st.info("No watchlist yet. Please click “Generate Watchlist” first.")

with tab2:
    st.subheader("Trade Plan")
    st.caption("This is a trading reference generated by the system based on position sizing and risk rules. It is not an automated execution order.")

    df = load_csv("reports/trade_plan.csv")
    if df is not None:
        rename_map = {
            "ticker": "Ticker",
            "plan_date": "Plan Date",
            "close": "Current Price",
            "score": "Score",
            "entry_price": "Reference Entry Price",
            "stop_price": "Reference Stop Price",
            "shares": "Suggested Shares",
            "note": "Notes",
        }
        df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})
        st.dataframe(df, use_container_width=True)
    else:
        st.info("No trade plan yet. Please click “Generate Trade Plan” first.")

with tab3:
    st.subheader("Backtest Results")
    st.caption("Backtesting helps evaluate whether these rules had some historical edge. Good backtest results do not guarantee future profitability.")

    st.markdown("### Single-Stock Backtest")
    df = load_csv("reports/backtest_metrics.csv")
    if df is not None:
        rename_map = {
            "run_date": "Run Date",
            "strategy_name": "Strategy Name",
            "ticker": "Ticker",
            "start_date": "Start Date",
            "end_date": "End Date",
            "final_value": "Ending Value",
            "total_return": "Total Return",
            "max_drawdown": "Max Drawdown",
            "sharpe": "Sharpe Ratio",
        }
        df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})
        st.dataframe(df, use_container_width=True)
    else:
        st.info("No single-stock backtest results yet. Please run a backtest first.")

    st.markdown("### Portfolio Backtest")
    portfolio_df = load_csv("reports/backtest_portfolio_metrics.csv")
    if portfolio_df is not None:
        rename_map = {
            "run_date": "Run Date",
            "strategy_name": "Strategy Name",
            "ticker": "Ticker",
            "start_date": "Start Date",
            "end_date": "End Date",
            "final_value": "Ending Value",
            "total_return": "Total Return",
            "max_drawdown": "Max Drawdown",
            "sharpe": "Sharpe Ratio",
        }
        portfolio_df = portfolio_df.rename(columns={k: v for k, v in rename_map.items() if k in portfolio_df.columns})
        st.dataframe(portfolio_df, use_container_width=True)
    else:
        st.info("No portfolio backtest results yet. Please run a portfolio backtest first.")

    st.markdown("### Portfolio Equity Curve")
    eq_df = load_csv("reports/backtest_portfolio_equity.csv")
    if eq_df is not None and not eq_df.empty:
        eq_df["date"] = pd.to_datetime(eq_df["date"])
        eq_df = eq_df.set_index("date")
        st.line_chart(eq_df["equity"])
    else:
        st.info("No portfolio equity curve available yet.")

with tab4:
    st.subheader("Filing Summaries")
    st.caption("This section displays the latest filing information and brief financial summaries pulled and organized from SEC EDGAR.")

    df = load_csv("reports/edgar_summary.csv")
    if df is not None:
        show_cols = [
            "ticker",
            "security_type",
            "form",
            "filing_date",
            "revenue",
            "net_income",
            "assets",
            "liabilities",
            "summary",
        ]
        existing_cols = [c for c in show_cols if c in df.columns]
        display_df = df[existing_cols].copy()

        rename_map = {
            "ticker": "Ticker",
            "security_type": "Type",
            "form": "Form",
            "filing_date": "Filing Date",
            "revenue": "Revenue",
            "net_income": "Net Income",
            "assets": "Total Assets",
            "liabilities": "Total Liabilities",
            "summary": "English Summary",
        }
        display_df = display_df.rename(columns={k: v for k, v in rename_map.items() if k in display_df.columns})
        st.dataframe(display_df, use_container_width=True)

        st.markdown("### Links to Latest Filings")
        for _, row in df.iterrows():
            ticker = row.get("ticker", "")
            filing_url = row.get("filing_url", "")
            summary = row.get("summary", "")

            st.markdown(f"**{ticker}**")
            if pd.notna(filing_url) and filing_url:
                st.markdown(f"[Open Latest Filing]({filing_url})")
            st.write(summary)
            st.divider()
    else:
        st.info("No filing summaries yet. Please click “Update Filing Summaries” first.")

with tab5:
    st.subheader("Trade Journal")
    st.caption("This section records your actual trades. The more complete your journal is, the more valuable your weekly review will be.")

    st.markdown("### Add a New Trade")
    with st.form("add_trade_form"):
        c1, c2, c3 = st.columns(3)

        with c1:
            trade_date = st.date_input("Trade Date")
            ticker = st.text_input("Ticker", value="AAPL")
            side = st.selectbox("Side", ["BUY", "SELL"])

        with c2:
            entry_price = st.number_input("Entry / Exit Price", min_value=0.0, value=100.0, step=0.01)
            shares = st.number_input("Shares", min_value=1, value=10, step=1)
            stop_price = st.number_input("Planned Stop Price", min_value=0.0, value=95.0, step=0.01)

        with c3:
            planned_target = st.number_input("Planned Target Price", min_value=0.0, value=110.0, step=0.01)
            setup_tag = st.text_input("Trade Setup Tag", value="trend_pullback")
            execution_grade = st.selectbox("Execution Grade", ["A", "B", "C", "D"])

        thesis = st.text_area("Trade Thesis", value="Why are you taking this trade?")
        submitted = st.form_submit_button("Save Trade")

        if submitted:
            add_trade(
                {
                    "trade_date": str(trade_date),
                    "ticker": ticker.upper(),
                    "side": side,
                    "entry_price": float(entry_price),
                    "shares": int(shares),
                    "stop_price": float(stop_price),
                    "planned_target": float(planned_target),
                    "thesis": thesis,
                    "setup_tag": setup_tag,
                    "execution_grade": execution_grade,
                }
            )
            st.success("Trade saved successfully")

    st.markdown("### Close an Existing Trade")
    journal_df = load_journal()
    open_df = journal_df[journal_df["exit_date"].isna()] if not journal_df.empty else pd.DataFrame()

    if not open_df.empty:
        trade_options = {
            f'#{row["id"]} {row["trade_date"]} {row["ticker"]} @ {row["entry_price"]}': int(row["id"])
            for _, row in open_df.iterrows()
        }

        with st.form("close_trade_form"):
            selected = st.selectbox("Select a trade to close", list(trade_options.keys()))
            exit_date = st.date_input("Exit Date")
            exit_price = st.number_input("Exit Price", min_value=0.0, value=100.0, step=0.01)
            review_note = st.text_area("Reason for Exit / Review Notes", value="Why are you exiting now?")
            close_submitted = st.form_submit_button("Confirm Close")

            if close_submitted:
                close_trade(
                    trade_options[selected],
                    str(exit_date),
                    float(exit_price),
                    review_note,
                )
                st.success("Trade closed successfully")
    else:
        st.info("There are currently no open trades.")

    st.markdown("### All Trade Records")
    journal_df = load_journal()
    if not journal_df.empty:
        rename_map = {
            "id": "ID",
            "trade_date": "Trade Date",
            "ticker": "Ticker",
            "side": "Side",
            "entry_price": "Entry Price",
            "shares": "Shares",
            "stop_price": "Stop Price",
            "planned_target": "Target Price",
            "thesis": "Trade Thesis",
            "setup_tag": "Tag",
            "execution_grade": "Execution Grade",
            "exit_date": "Exit Date",
            "exit_price": "Exit Price",
            "pnl": "PnL",
            "review_note": "Review Notes",
            "planned_stop_hit": "Planned Stop Hit",
            "exit_discipline": "Exit Type",
        }
        journal_df = journal_df.rename(columns={k: v for k, v in rename_map.items() if k in journal_df.columns})
        st.dataframe(journal_df, use_container_width=True)
    else:
        st.info("No trade records yet.")

with tab6:
    st.subheader("Weekly Review")
    st.caption("This section combines your trade results, execution quality, and portfolio performance to help identify where problems are coming from.")

    if st.button("Generate Weekly Review"):
        r = run_py("src/weekly_review.py")
        if r.returncode == 0:
            st.success("Weekly review generated successfully")
        else:
            st.error(r.stderr or r.stdout)

    review_df = load_csv("reports/weekly_review.csv")
    if review_df is not None:
        rename_map = {
            "review_date": "Review Date",
            "new_trades": "New Trades This Week",
            "closed_trades": "Closed Trades This Week",
            "weekly_realized_pnl": "Weekly Realized PnL",
            "summary": "Summary",
        }
        review_df = review_df.rename(columns={k: v for k, v in rename_map.items() if k in review_df.columns})
        st.dataframe(review_df, use_container_width=True)
    else:
        st.info("No weekly review yet. Please click “Generate Weekly Review” first.")

    diag_df = load_csv("reports/weekly_diagnostics.csv")
    if diag_df is not None and not diag_df.empty:
        st.markdown("### Automated Diagnostics")
        rename_map = {
            "metric": "Metric",
            "value": "Value",
            "comment": "Comment",
        }
        diag_df = diag_df.rename(columns={k: v for k, v in rename_map.items() if k in diag_df.columns})
        st.dataframe(diag_df, use_container_width=True)
    else:
        st.info("No diagnostics data yet.")

    journal_df = load_journal()
    if journal_df is not None and not journal_df.empty:
        journal_df["trade_date"] = pd.to_datetime(journal_df["trade_date"], errors="coerce")
        journal_df["exit_date"] = pd.to_datetime(journal_df["exit_date"], errors="coerce")

        week_start = pd.Timestamp.today().normalize() - pd.Timedelta(days=7)

        weekly_closed = journal_df[
            journal_df["exit_date"].notna() & (journal_df["exit_date"] >= week_start)
        ].copy()

        if not weekly_closed.empty:
            st.markdown("### Weekly Closed Trade PnL Chart")
            chart_df = weekly_closed[["ticker", "pnl"]].copy()
            chart_df = chart_df.set_index("ticker")
            st.bar_chart(chart_df["pnl"])

        if "execution_grade" in journal_df.columns:
            weekly_new = journal_df[journal_df["trade_date"] >= week_start].copy()
            if not weekly_new.empty:
                grade_chart = (
                    weekly_new["execution_grade"]
                    .fillna("N/A")
                    .value_counts()
                    .sort_index()
                    .rename_axis("grade")
                    .reset_index(name="count")
                )
                st.markdown("### Weekly Execution Grade Distribution")
                st.bar_chart(grade_chart.set_index("grade")["count"])

    eq_df = load_csv("reports/backtest_portfolio_equity.csv")
    if eq_df is not None and not eq_df.empty:
        st.markdown("### Portfolio Equity Curve")
        eq_df["date"] = pd.to_datetime(eq_df["date"])
        eq_df = eq_df.set_index("date")
        st.line_chart(eq_df["equity"])

    if os.path.exists("reports/weekly_review.txt"):
        st.markdown("### Text Review")
        with open("reports/weekly_review.txt", "r", encoding="utf-8") as f:
            st.text(f.read())
    else:
        st.info("No text review available yet.")
