import os
import pandas as pd
import numpy as np

ACCOUNT_SIZE = 100000
RISK_PER_TRADE = 0.01   # risk 1% of account per trade
MAX_POS_PCT = 0.10      # max 10% of account per position

WATCHLIST_PATH = "reports/watchlist.csv"
OUTPUT_PATH = "reports/trade_plan.csv"


def main():
    if not os.path.exists(WATCHLIST_PATH):
        print(f"Missing file: {WATCHLIST_PATH}")
        return

    df = pd.read_csv(WATCHLIST_PATH)

    if df.empty:
        print("Watchlist is empty.")
        return

    required_cols = ["ticker", "close", "score"]
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        print(f"Missing required columns in watchlist.csv: {missing_cols}")
        return

    plans = []

    for _, row in df.iterrows():
        ticker = str(row.get("ticker", "")).upper().strip()
        close = row.get("close", np.nan)
        score = row.get("score", np.nan)

        # Validate basic fields
        if pd.isna(close) or close <= 0:
            print(f"Skip {ticker}: invalid close price -> {close}")
            continue

        # Example rule:
        # entry price = current close
        # stop price = 5% below entry
        entry_price = float(close)
        stop_price = round(entry_price * 0.95, 2)

        # Per-share risk
        risk_ps = entry_price - stop_price

        # Defensive checks
        if pd.isna(entry_price) or pd.isna(stop_price):
            print(f"Skip {ticker}: entry or stop is NaN")
            continue

        if pd.isna(risk_ps) or risk_ps <= 0:
            print(f"Skip {ticker}: invalid risk per share -> {risk_ps}")
            continue

        # Shares based on risk budget
        shares_by_risk = int((ACCOUNT_SIZE * RISK_PER_TRADE) / risk_ps)

        # Shares based on max position size
        shares_by_cap = int((ACCOUNT_SIZE * MAX_POS_PCT) / entry_price)

        shares = min(shares_by_risk, shares_by_cap)

        if shares <= 0:
            print(f"Skip {ticker}: calculated shares <= 0")
            continue

        plan = {
            "ticker": ticker,
            "plan_date": pd.Timestamp.today().strftime("%Y-%m-%d"),
            "close": round(entry_price, 2),
            "score": score,
            "entry_price": round(entry_price, 2),
            "stop_price": round(stop_price, 2),
            "risk_per_share": round(risk_ps, 2),
            "shares": shares,
            "position_value": round(shares * entry_price, 2),
            "max_risk_amount": round(shares * risk_ps, 2),
            "note": "Generated by rule-based trade plan",
        }

        plans.append(plan)

    if not plans:
        print("No valid trade plans generated.")
        return

    out_df = pd.DataFrame(plans)
    out_df = out_df.sort_values(by="score", ascending=False, na_position="last")

    os.makedirs("reports", exist_ok=True)
    out_df.to_csv(OUTPUT_PATH, index=False)

    print(f"Trade plan saved to {OUTPUT_PATH}")
    print(out_df.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
